#ifndef __COLLISION_LAYER_H__
#define __COLLISION_LAYER_H__

#define COLLISION_LAYER_ENEMY 0b100
#define COLLISION_LAYER_MAIN_CHAR 0b10
#define COLLISION_LAYER_WORLD 0b1
#define COLLISION_LAYER_ALL 0xFFFFFFFF

#endif // __COLLISION_LAYER_H__