#ifndef __SCENE_TAGS_H__
#define __SCENE_TAGS_H__

typedef enum SceneType {
    SCENE_TYPE_UNKNOWN = 0,
    SCENE_TYPE_EMPTY,
    SCENE_TYPE_BLOCK,
    SCENE_TYPE_MAIN_CHAR,
    SCENE_TYPE_MAIN_CHAR_FOOT,
    SCENE_TYPE_MAIN,
    SCENE_TYPE_COLLIDER,
    SCENE_TYPE_RAYCAST,
    SCENE_TYPE_MAIN_CHAR_HAND,
    SCENE_TYPE_MAIN_CHAR_EYE,
    SCENE_TYPE_MAIN_CHAR_GUN,
    SCENE_TYPE_MAIN_CHAR_JETPACK_FIRE,
    SCENE_TYPE_MAIN_CHAR_BULLET,
    SCENE_TYPE_SPRITE,
    SCENE_TYPE_ANIMATED_SPRITE,
    SCENE_TYPE_SPRING_ARM,
} SceneType;

#endif // __SCENE_TAGS_H__